apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: adam-tap-test-app
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: adam-tap-test-app
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_ssh_secret
    value: ssh-credentials
  source:
    git:
      url: ssh://git@github.com:22/adam-power/adam-tap-test-app.git
      ref:
        branch: main
